### ISSUE TITLE
"Internal Server Error"

### ISSUE THREAD

**Issue by aleckarlo** [mlab817/q-pipol#50] opened 2020-06-10 03:18 UTC
After OUs were assigned by the "superadmin", the "reviewer" user cannot log in anymore and an "internal server error" notification popped-up.

**Comment by mlab817** [comment] 2020-06-11 02:00
Fixed in 835ea63

This issue was caused by malformed query as instead of returning an array, models are being returned in the ProjectScope.

**Closed by mlab817** 2020-06-11 02:00 UTC
Labels: bug
